language: node_js
sudo: false
node_js:
  - 6
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: olegman/style-node-loader
